/* This file is autogenerated by grm -- do not edit. */

#ifndef UNITY_INCLUDE_CONFIG_H
#error "Must define UNITY_INCLUDE_CONFIG_H."
#endif

/*** Standard includes. ***/
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>

#include "unity.h"

/*** Stuff copied from test files (should be #include's, declarations & macros only) ***/
#include "testOne.h"

/*** External test functions scraped from test files. ***/
void test_none_1_a();
void test_none_1_b();
void test_setup();
void test_none_1_c();
void test_dump_ok();
void test_dump_fail();
void test_setup_teardown();
void test_teardown();
void test_1f(int x);
void test_none_2_a();
void test_none_2_b();

/*** Fixture & dump functions from test files. ***/
void dumpOne(void);

/* Declare test stubs. */
static void test_1f_stub_0(void) { test_1f(0); }
static void test_1f_stub_1(void) { test_1f(1); }

/*** Extra Unity support. ***/

/* Functions for setup, diagnostics dump on a test failure & teardown. */
typedef void (*fixture_func_t)(void);
static fixture_func_t setUp_func, dump_func, tearDown_func;
void registerFixture(fixture_func_t setup, fixture_func_t dumper, fixture_func_t teardown) {
	setUp_func = setup;
	dump_func = dumper;
	tearDown_func = teardown;
}

void setUp() { if (setUp_func) setUp_func(); }
void dumpTestContext() { if (dump_func) dump_func(); }
void tearDown() { if (tearDown_func) tearDown_func(); }

static void do_run_test(UnityTestFunction func, const char* name, int line_num) {
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
	UnityDefaultTestRun(func, name, line_num);
}

int main(int argc, char** argv) {
/*
	int rc_parse = UnityParseOptions(argc,argv);
	if (rc_parse != 0)
		return rc_parse;
*/
  UnityBegin("");
  
  UnitySetTestFile("testOne.c");
  do_run_test(test_none_1_a, "test_none_1_a", 6);
  do_run_test(test_none_1_b, "test_none_1_b", 7);
  do_run_test(test_setup, "test_setup", 10);
  registerFixture(NULL, NULL, NULL);
  do_run_test(test_none_1_c, "test_none_1_c", 13);
  registerFixture(NULL, dumpOne, NULL);
  do_run_test(test_dump_ok, "test_dump_ok", 16);
  do_run_test(test_dump_fail, "test_dump_fail", 17);
  registerFixture(NULL, NULL, NULL);
  do_run_test(test_setup_teardown, "test_setup_teardown", 21);
  do_run_test(test_teardown, "test_teardown", 24);
  registerFixture(NULL, NULL, NULL);
  do_run_test(test_1f_stub_0, "test_1f(0)", 29);
  do_run_test(test_1f_stub_1, "test_1f(1)", 30);
  
  UnitySetTestFile("test_two.c");
  do_run_test(test_none_2_a, "test_none_2_a", 3);
  do_run_test(test_none_2_b, "test_none_2_b", 4);

  return UnityEnd();
}

/*

*/
